[[language]]
name = "bash"
scope = "source.bash"
file-types = ["sh", "bash", ".bashrc", ".bash_profile", ".bash_login", ".bash_logout"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = ["bash-language-server"]
auto-format = true

[language-server.bash-language-server]
command = "bash-language-server"
args = ["start"]
