# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: kluster
clients:
- type: openai-compatible
  name: kluster
  api_base: https://api.kluster.ai/v1/
  api_key: b45aa1db-7998-4993-88cf-6145c8199b56
  models:
  - name: deepseek-ai/DeepSeek-R1
